name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "pnpm"

      - name: Install all dependencies
        run: pnpm --filter manager install

      - name: Run Semantic Release
        run: pnpm --filter manager release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
